### ISSUE TITLE
 ## Todo ##

### ISSUE THREAD

**Issue by tobiasandersen01** [tobiasandersen01/rof-i3-rice#2]
- [ ] Make py3bar VPN plugin work on, it currently is not working.
- [ ] Improve man pages: clickable links.
- [ ] At screen edges (top or bot) i3 does not handle more than one bar at a time properly.
- [ ] *Is it possible to implement a bar with rows insted?*
- [ ] Continue work on Conky, improving layout.
- [ ] Convert Conkyfiles to LUA.
- [ ] Rework [rofimoji](https://github.com/fdw/rofimoji) (bugged).
- [ ] Make a keybind for 'sudo !!'
